dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
  solc:
    version: 0.8.11
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2"
networks:
  
  polygon-main:
    token_names:
      - "WMATIC"
      - "USDC"
      - "DAI"
      - "LINK"
      - "WBTC"
      - "WETH"
      - "USDT"
      - "COMP"
      - "CEL"
      - "AAVE"
      - "CRV"
      - "QI"
      - "quick"
      - "sushi"
      - "dyfn"
      - "bifi"
      - "avax"
      - "addy"
      - "bal"
      - "uni"
      - "mana"
      #- "ust"
      - "sand"
      - "snx"
      - "1inch"
      - "yfi"

    token_addresses:
      WMATIC: "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270" 
      USDC: "0x2791bca1f2de4661ed88a30c99a7a9449aa84174"
      DAI: "0x8f3cf7ad23cd3cadbd9735aff958023239c6a063"
      LINK: "0x53e0bca35ec356bd5dddfebbd1fc0fd03fabad39"
      WBTC: "0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6"
      WETH: "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619"
      USDT: "0xc2132d05d31c914a87c6611c10748aeb04b58e8f"
      COMP: "0x8505b9d2254a7ae468c0e9dd10ccea3a837aef5c"
      CEL: "0xd85d1e945766fea5eda9103f918bd915fbca63e6"
      UNI: "0xb33eaad8d922b1083446dc23f610c2567fb5180f"
      AAVE: "0xd6df932a45c0f255f85145f286ea0b292b21c90b"
      CRV: "0x172370d5cd63279efa6d502dab29171933a610af"
      QI: "0x580a84c73811e1839f75d86d75d88cca0c241ff4"
      quick: "0xb5c064f955d8e7f38fe0460c556a72987494ee17"
      sushi: "0x0b3F868E0BE5597D5DB7fEB59E1CADBb0fdDa50a"
      dyfn: "0xC168E40227E4ebD8C1caE80F7a55a4F0e6D66C97"
      bifi: "0xFbdd194376de19a88118e84E279b977f165d01b8"
      avax: "0x2C89bbc92BD86F8075d1DEcc58C7F4E0107f286b"
      addy: "0xc3FdbadC7c795EF1D6Ba111e06fF8F16A20Ea539"
      bal: "0x9a71012B13CA4d3D0Cdc72A177DF3ef03b0E76A3"
      uni: "0xb33EaAd8d922B1083446DC23f610c2567fB5180f"
      mana: "0xA1c57f48F0Deb89f569dFbE6E2B7f46D33606fD4"
      #ust: "0x692597b009d13C4049a947CAB2239b7d6517875F"
      sand: "0xBbba073C31bF03b8ACf7c28EF0738DeCF3695683"
      snx: "0x50B728D8D964fd00C2d0AAD81718b71311feF68a"
      1inch: "0x9c2C5fd7b07E95EE044DDeba0E97a665F142394f"
      yfi: "0xDA537104D6A5edd53c6fBba9A898708E465260b6"

    coingecko_ids:
      - "matic-network"
      - "usd-coin"
      - "dai"
      - "chainlink"
      - "bitcoin"
      - "ethereum"
      - "tether"
      - "compound-governance-token"
      - "celsius-degree-token"
      - "uniswap"
      - "aave"
      - "curve-dao-token"
      - "qi-dao"
      - "quickswap"
      - "sushi"
      - "dfyn-network"
      - "beefy-finance"
      - "avalanche-2"
      - "adamant"
      - "balancer"
      - "uniswap"
      - "decentraland"
      - "the-sandbox"
      - "havven"
      - "1inch"
      - "yearn-finance"
    dexes:
      names:
        - "quickswap"
        - "sushiswap"
        - "apeswap"
        - "dfyn"
        - "jetswap"
        - "waltswap"
        
        
      quickswap:
        fee: 0.3
        approx_slippage: 0.1
        swap_router_V2_address: "0xa5E0829CaCEd8fFDD4De3c43696c57F7D7A678ff"
        uniswap_factory_address: "0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"
      sushiswap:
        fee: 0.3
        approx_slippage: 0.1
        swap_router_V2_address: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"
        uniswap_factory_address: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4"
      apeswap:
        fee: 0.3
        approx_slippage: 0.1
        swap_router_V2_address: "0xC0788A3aD43d79aa53B09c2EaCc313A787d1d607"
        uniswap_factory_address: "0xCf083Be4164828f00cAE704EC15a36D711491284"  
      dfyn:
        fee: 0.3
        approx_slippage: 0.1
        swap_router_V2_address: "0xA102072A4C07F06EC3B4900FDC4C7B80b6c57429"
        uniswap_factory_address: "0xE7Fb3e833eFE5F9c441105EB65Ef8b261266423B"
      jetswap:
        fee: 0.3
        approx_slippage: 0.1
        swap_router_V2_address: "0x5C6EC38fb0e2609672BDf628B1fD605A523E5923"
        uniswap_factory_address: "0x668ad0ed2622C62E24f0d5ab6B6Ac1b9D2cD4AC7" 
      waltswap:
        fee: 0.3
        approx_slippage: 0.1
        swap_router_V2_address: "0x3a1D87f206D12415f5b0A33E786967680AAb4f6d"
        uniswap_factory_address: "0xa98ea6356A316b44Bf710D5f9b6b4eA0081409Ef"     
  
        settings:
        gas_price: "100000000000"

        
